'use strict'

/**
 * Seeds a demo batch so a fresh clone has something to look at.
 *
 *   node --env-file=.env scripts/seed_demo.js
 *
 * Generates small placeholder images, ingests them, and runs the mock
 * recognition provider — which produces a realistic spread of confidences, so
 * the review queue, the correction UI and the export all have real work to do.
 *
 * Refuses to run against a database that already has batches. Seed data mixed
 * into real data is a support ticket six months later ("who is Acme Ltd?").
 */

const fs = require('node:fs')
const path = require('node:path')
const zlib = require('node:zlib')

const { loadConfig } = require('../lib/config')
const { createContainer } = require('../server/container')

const DOCUMENT_COUNT = Number(process.env.SEED_DOCUMENT_COUNT || 12)

const PAGE_WIDTH = 420
const PAGE_HEIGHT = 560

/**
 * Generates a real, decodable PNG rather than shipping sample scans.
 *
 * No image file is committed on purpose: a public repository is exactly where
 * someone's actual paperwork should never end up. Generating them means the
 * viewer shows a genuine image — a broken-image icon in the review workspace
 * looks like the app is broken, which is a bad first impression of a skeleton
 * whose whole job is to be a good first impression.
 *
 * Hand-rolled because a PNG is honestly not much: an 8-byte signature and
 * three length-type-data-CRC chunks. `sharp` or `jimp` would do this too, and
 * would be a dependency the running application never needs.
 */
const CRC_TABLE = (() => {
  const table = new Int32Array(256)
  for (let n = 0; n < 256; n += 1) {
    let c = n
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    table[n] = c
  }
  return table
})()

function crc32(buffer) {
  let crc = -1
  for (const byte of buffer) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8)
  return (crc ^ -1) >>> 0
}

function pngChunk(type, data) {
  const length = Buffer.alloc(4)
  length.writeUInt32BE(data.length)
  const typeAndData = Buffer.concat([Buffer.from(type, 'ascii'), data])
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(typeAndData))
  return Buffer.concat([length, typeAndData, crc])
}

/**
 * A greyscale page that reads as a document: a light sheet with darker bands
 * where text would be. Varied per index so each file hashes differently —
 * identical bytes would (correctly) be deduplicated by intake, and the seed
 * would end up with one document instead of twelve.
 */
function placeholderPng(index) {
  const header = Buffer.alloc(13)
  header.writeUInt32BE(PAGE_WIDTH, 0)
  header.writeUInt32BE(PAGE_HEIGHT, 4)
  header[8] = 8 // bit depth
  header[9] = 0 // colour type: greyscale
  // 10-12 are compression, filter and interlace — all zero, all required.

  // Each scanline is one filter byte followed by one grey byte per pixel, so
  // pixel x lives at rowStart + 1 + x. Writing it at rowStart + x instead
  // clobbers the filter byte with a pixel value: the file still inflates and
  // `file` still reports a valid PNG, but the filter type is now nonsense and
  // a real decoder renders nothing. That produced a silently blank image.
  const raw = Buffer.alloc(PAGE_HEIGHT * (PAGE_WIDTH + 1))
  for (let y = 0; y < PAGE_HEIGHT; y += 1) {
    const rowStart = y * (PAGE_WIDTH + 1)
    raw[rowStart] = 0 // filter type: none
    for (let x = 0; x < PAGE_WIDTH; x += 1) {
      const margin = x < 40 || x > PAGE_WIDTH - 40 || y < 48 || y > PAGE_HEIGHT - 48
      // Text bands every 34px, of varying length, offset by the index so no
      // two pages look identical.
      const inBand = !margin && y % 34 < 9 && x < 60 + ((y * 7 + index * 53) % (PAGE_WIDTH - 140))
      raw[rowStart + 1 + x] = margin ? 0xf2 : inBand ? 0x3a : 0xfa
    }
  }

  return Buffer.concat([
    Buffer.from('89504e470d0a1a0a', 'hex'),
    pngChunk('IHDR', header),
    pngChunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    pngChunk('IEND', Buffer.alloc(0)),
  ])
}

async function main() {
  const config = loadConfig({ projectRoot: path.join(__dirname, '..') })
  const container = createContainer({ config })

  try {
    const existing = container.repositories.batches.list({ limit: 1 })
    if (existing.total > 0) {
      process.stderr.write(
        `Refusing to seed: ${existing.total} batch(es) already exist.\n` +
          'Point STORAGE_ROOT at an empty directory, or delete the database first.\n'
      )
      process.exit(1)
    }

    const businessDay = new Date().toISOString().slice(0, 10)
    const batchId = `demo-${businessDay}`
    container.repositories.batches.create({
      id: batchId,
      label: 'Demo batch',
      businessDay,
      notes: 'Generated by scripts/seed_demo.js — safe to delete.',
    })

    // Written to the temp upload directory in the shape multer produces, so
    // the seed exercises the real intake path rather than a parallel one that
    // can drift out of step with it.
    const files = []
    for (let index = 0; index < DOCUMENT_COUNT; index += 1) {
      const filePath = path.join(config.storage.tmpUploadRoot, `seed-${index}.png`)
      fs.writeFileSync(filePath, placeholderPng(index))
      files.push({
        path: filePath,
        originalname: `scan_${String(index + 1).padStart(3, '0')}.png`,
        size: fs.statSync(filePath).size,
      })
    }

    const intake = await container.services.intake.ingest({ batchId, files })
    process.stdout.write(`Ingested ${intake.accepted.length} documents into ${batchId}.\n`)

    const { jobId } = container.services.recognitionStage.start({ batchId })
    process.stdout.write(`Recognition job ${jobId} started. Waiting…\n`)

    // The stage runs in the background, so poll the job row rather than
    // guessing at a sleep duration.
    const deadline = Date.now() + 60_000
    let job = container.stageRunner.getJob(jobId)
    while (!job.isTerminal && Date.now() < deadline) {
      await new Promise((resolve) => setTimeout(resolve, 250))
      job = container.stageRunner.getJob(jobId)
    }

    const queue = container.repositories.documents.reviewQueue({ batchId, limit: 100 })
    process.stdout.write(
      `Job ${job.status}. ${queue.length} document(s) need review.\n\n` +
        `Start the server and open http://${config.server.host}:${config.server.port}\n`
    )
  } finally {
    container.close()
  }
}

main().catch((error) => {
  process.stderr.write(`${error?.stack || error}\n`)
  process.exit(1)
})
